app = "flaskproject-nameless-feather-9941"
primary_region = "iad"

[http_service]
  internal_port = 5006
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4

