# fly.toml app configuration file generated for flaskproject-nameless-feather-9941 on 2024-11-13T11:26:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flaskproject-nameless-feather-9941"
primary_region = "iad"

[http_service]
  internal_port = 5006  # Updated to match Flask's default port
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "5000"  # Set environment variable for Flask's port

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 4
